from backend.graph.nodes.resume_parser_node import resume_parser_node
from backend.graph.nodes.skill_match_analyze_node import skill_match_analyze_node
from backend.graph.nodes.career_analyze_node import career_analyze_node
from backend.graph.nodes.self_intro_analyze_node import self_intro_analyze_node
from backend.graph.nodes.personal_info_analyze_node import personal_info_analyze_node
from backend.graph.nodes.photo_analyze_node import photo_analyze_node
from backend.graph.nodes.aggregator_node import aggregator_node
